### ISSUE TITLE
Offer GeoLite2 as a service rather than distributing to clients

### ISSUE THREAD

**Issue by deanveloper** [track/plugin#10]
Reference: https://github.com/track/plugin/issues/8#issuecomment-1048096490

In order to comply with this part of the license, you should likely offer your own geolocation endpoint.
> Security of the Services. You will maintain reasonable and appropriate technical and organizational measures for the protection of the security, confidentiality, and integrity of the Services
> [...]
> Destructions of GeoLite2 Database and GeoLite2 Data. From time to time, MaxMind will release an updated version of the GeoLite2 Databases, and you agree to promptly use the updated version of the GeoLite2 Databases. You shall cease use of and destroy (i) any old versions of the Services within thirty (30) days following the release of the updated GeoLite2 Databases; and (ii) all Services immediately upon termination of the license under this Agreement. Upon request, you shall provide MaxMind with written confirmation of such destruction.

Distributing the database to clients makes it quite complicated to update, and "updatability" is required by their license. It's probably better to keep one copy of the database in the backend, and have an endpoint that gives you the location of a user based on their IP.

**Comment by heychazza** [comment]
Resolved, https://github.com/track/plugin/commit/034b217a45e2479b21b20f96c00f6f31073820f6.
