### ISSUE TITLE
Potential DOS attack vector

### ISSUE THREAD

**Issue by deanveloper** [track/plugin#14]
https://github.com/track/plugin/blob/35cd4cc7cf43051ef2e18ab4ff55c8dd52c35544/src/main/java/net/analyse/plugin/commands/AnalyseCommand.java#L39

Networked request happening on the main thread, with a command that is available for anyone to use (I think).

Related to #13, same solutions apply:
1. ~~Replace Bukkit.getScheduler().runTaskAsynchronously with a more proper~~ Use ScheduledExecutorService. This is a good temporary and easy fix.
2. Have AnalyseSDK networked calls return CompletableFutures (which are similar to Javascript Promises). This is probably going to require a bit more work, but will result in better code down the line and reduce tech debt.

(also, should probably put this behind a permission. I didn't see anything permission-related to this command)

**Comment by heychazza** [comment]
Thank you, it's guarded behind a permission now.
