### ISSUE TITLE
Redis Compulsory Support

### ISSUE THREAD

**Issue by nathanielcutajar** [track/plugin#18]
Currently Redis is a requirement to use this plugin on Bungee. Is it not possible to have it built in using the in-memory variant?
And if you need to persist the data, why not use SQLite or MySQL (which usually servers would already have set up)

Having to set up Redis to use this on Bungee might not be possible for some as it might not be feasible, might not be allowed, or would not have the knowhow on how to set it up. In my case I have the whole server running inside Docker, which will require me to rebuild the whole image to now also include Redis.

**Comment by heychazza** [comment]
> Currently Redis is a requirement to use this plugin on Bungee. Is it not possible to have it built in using the in-memory variant? And if you need to persist the data, why not use SQLite or MySQL (which usually servers would already have set up)
> 
> Having to set up Redis to use this on Bungee might not be possible for some as it might not be feasible, might not be allowed, or would not have the knowhow on how to set it up. In my case I have the whole server running inside Docker, which will require me to rebuild the whole image to now also include Redis.

Hey Nathan,

Thanks for your message! I can agree Redis can be tedious, SQLite wouldn't work as the other servers wouldn't be able to retrieve it.

MySQL would certainly be an option but isn't a priority right now, we'd be happy to review a pull request if you or another developer wanted to integrate this.

Thanks for the feedback, it helps :)

**Comment by heychazza** [comment]
Hey there,

Just an update - we have begun work on the v2 version which will drop the need for Redis, thank you for this brilliant suggestion.
