### ISSUE TITLE
Repo illegally redistributes GeoLite2 database

### ISSUE THREAD

**Issue by mattyokan** [track/plugin#3]
GeoLite2 is provided in the ``src/main/resources`` folder of this repo, however, GeoLite2 prohibits this without attribution.

https://blog.maxmind.com/2019/12/significant-changes-to-accessing-and-using-geolite2-databases

For legal reasons you should consider removing this and rebasing or adding attribution to conform to GeoLite2's license.

**Comment by heychazza** [comment]
> 

Feel free to PR.

**Comment by mattyokan** [comment]
This project isn't open-source (if you intend it to be, you should add a license). Regardless, I can't rebase with a pull request (that's not how git works). Do it yourself.

**Comment by heychazza** [comment]
> This project isn't open-source: if you intend it to be, you should add a license. Regardless, I can't rebase with a pull request (that's not how git works). You will need to do it yourself if you wish to remove the database from the repository.

Ah no worries, thank you a ton!

**Comment by kev626** [comment]
> Feel free to PR.

Let’s not forget that this is your company, and a project that is only useful in the context of your paid product. It’s quite unfair for your response to criticism be “feel free to PR”. We don’t work for you.

**Comment by heychazza** [comment]
> > Feel free to PR.
> 
> Let’s not forget that this is your company, and a project that is only useful in the context of your paid product. It’s quite unfair for your response to criticism be “feel free to PR”. We don’t work for you.

Nice advice, thank you - will certainly look into it :)

**Comment by mattyokan** [comment]
This is still being distributed against the terms of the GeoLite2 license. It's certainly not resolved.

**Comment by heychazza** [comment]
> This is still being distributed against the terms of the GeoLite2 license. It's certainly not resolved.

It is, please see https://github.com/track/plugin/issues/8#issuecomment-1044875577

**Comment by deanveloper** [comment]
please don't take my words for gospel, if someone says there's still a licensing issue it's probably because they know better than me
