### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by deanveloper** [track/plugin#8]
# Attribution issues

You use several libraries which require attribution:
1. [trove4j uses LGPL](https://bitbucket.org/trove4j/trove/src/master/LICENSE.txt)
2. [GeoIP2 uses Apache 2.0](https://github.com/maxmind/GeoIP2-java/blob/main/LICENSE)
3. [okhttp uses Apache 2.0](https://square.github.io/okhttp/#license)
4. [gson uses Apache 2.0](https://github.com/google/gson/blob/master/LICENSE)
5. [jetbrains annotations uses Apache 2.0](https://github.com/JetBrains/java-annotations/blob/master/LICENSE.txt)

To properly attribute the libraries, the normal route is to add a `CREDITS.md` file which looks something like:

```````
# library-name

```
[entire copy of their license]
```

# library2-name

```
[entire copy of their license]
```
```````

# Copyleft issues

Also a couple libraries which require copyleft. I'm not sure how much these owners care, but I thought I might as well mention it, especially since this is commercial software:
1. [PlaceholderAPI uses GPL](https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/LICENSE)
2. [Spigot-API is GPL (although unenforced)](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/LICENCE.txt)

I would personally try to substitute PlaceholderAPI if possible. As stated earlier, I'm unsure if they actually care about the copyleft issue. Even if they don't care right now, if they decide to care later down the road, you may encounter a lot of technical debt issues when removing the dependency. However spigot-api doesn't seem to really enforce their copyleft, so it may be okay to continue using a non-GPL license while depending on spigot (not necessarily legal).

## Disclaimer

I am not a lawyer. My recommendations are not necessarily legal and I'm not liable for whatever choice you make, including (and not limited to) your choice about the copyleft licensing

(edit - reorganized and clarified that i am not a lawyer)

**Comment by deanveloper** [comment]
Also, according to the [GeoIP2 site license](https://www.maxmind.com/en/site-license-overview), you cannot disclose location information to third parties (ie, your customers), even if they are aggregated. The API is solely to be used for "Internal Restricted Business Purposes" (ie localization or fraud detection) and cannot be used outside of the company and its employees.

**Comment by deanveloper** [comment]
GeoLite2 uses a custom license: https://www.maxmind.com/en/geolite2/eula

Some highlights from their license (I do suggest reading it yourself):

Attribution is required
> You must provide attribution of your use to MaxMind (an example of attribution: "This product includes GeoLite2 Data created by MaxMind, available from https://www.maxmind.com/").

It may be good to offer this as a private API rather than distributing the database to clients. I'll make a new issue for this since this is a bit of a bigger feat than just adding attributions.
> Security of the Services. You will maintain reasonable and appropriate technical and organizational measures for the protection of the security, confidentiality, and integrity of the Services
> [...]
> Destructions of GeoLite2 Database and GeoLite2 Data. From time to time, MaxMind will release an updated version of the GeoLite2 Databases, and you agree to promptly use the updated version of the GeoLite2 Databases. You shall cease use of and destroy (i) any old versions of the Services within thirty (30) days following the release of the updated GeoLite2 Databases; and (ii) all Services immediately upon termination of the license under this Agreement. Upon request, you shall provide MaxMind with written confirmation of such destruction.

**Comment by heychazza** [comment]
Resolved, https://github.com/track/plugin/commit/034b217a45e2479b21b20f96c00f6f31073820f6.

**Comment by deanveloper** [comment]
Do you mind re-opening the issue? The thing that the issue was initially targeting (attribution for libraries which require it) doesn't seem to be resolved yet
