### ISSUE TITLE
Enhancement - reuse the DatabaseReader in LocationUtil

### ISSUE THREAD

**Issue by deanveloper** [track/plugin#9]
https://github.com/track/plugin/blob/main/src/main/java/net/analyse/plugin/util/LocationUtil.java#L20

Currently, you are creating a new DatabaseReader every time you call `LocationUtil#fromIp`. This means opening the file every time the database is used.

I would recommend storing a single DatabaseReader and reusing it in each `fromIp` call. I'm unsure if DatabaseReader is designed to be thread-safe, so I'd recommend wrapping in a mutex or using `ThreadLocal<DatabaseReader>` instead of a single `DatabaseReader`.

**Comment by deanveloper** [comment]
Sick, then there shouldn't be any worry for needing to use thread-local storage

**Comment by heychazza** [comment]
Thanks for the suggestion Dean, implemented :)

https://github.com/track/plugin/commit/f2579315d4d7cfb02e64ab21b7c4a45975da1c27
